sigmageo_root/editing/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('add_task', views.add_task),
  path('edit_task', views.redact_task),
  path('add_section', views.add_section),
  path('edit_section', views.redact_section),
  path('<str:a>', views.p404),
]

sigmageo_root/latex/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.task_list),
  path('compile', views.compile),
  path('<str:a>', views.p404),
]

sigmageo_root/sigmageo_site/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('favicon.ico', RedirectView.as_view(url = '/static/images/favicon.ico', permanent = True)),
    path('sigma_geo/latex/', include('latex.urls')),
    path('sigma_geo/editing/', include('editing.urls')),
    path('sigma_geo/feedback/', include('feedback.urls')),
    path('sigma_geo/auth/', include('login.urls')),
    path('sigma_geo/', include('collection.urls')),
    path('', include('pages.urls')),
]

sigmageo_root/collection/models.py
from django.db import models

# Create your models here.
class UserTexList(models.Model):
  username = models.CharField(primary_key=True, max_length=120)
  tex_list = models.TextField(null=True)

  def __str__():
    return self.username


class Problem(models.Model):
  id = models.IntegerField(primary_key=True)
  num = models.CharField(max_length=5, default='')
  grade = models.CharField(max_length=5)
  text = models.TextField(null=False)
  solution = models.TextField(default='')
  themes = models.TextField(default='[]')
  source = models.CharField(max_length=250, default='')
  year = models.CharField(max_length = 20, null=True)
  stage = models.CharField(max_length=150, default='')
  author = models.CharField(max_length=150, default='')
  dif = models.IntegerField(choices={i : i for i in range(11)})


class Olimp(models.Model):
  id = models.IntegerField(primary_key=True)
  name = models.CharField(max_length=250, null=False)
  stages = models.TextField(default='[]')


class Book(models.Model):
  id = models.IntegerField(primary_key=True)
  name = models.CharField(max_length=250, null=False)
  chapters = models.TextField(default='[]')

class Theme(models.Model):
  id = models.IntegerField(primary_key=True)
  name = models.CharField(max_length=250, null=False)
  description = models.TextField(null=True)
  edu_tasks = models.TextField(default='[]')

sigmageo_root/editing/models.py
from django.db import models

# Create your models here.

sigmageo_root/editing/forms.py
from django import forms
from collection.models import Problem

class TaskEditor(forms.ModelForm):

  class Meta:
    model = Problem
    fields = '__all__'
    widgets = {}
    labels = {
      'num' : 'Номер',
      'grade' : 'Класс',
      'text' : 'Условие',
      'solution' : 'Решение',
      'themes' : 'Темы',
      'source' : 'Источник',
      'year' : 'Год',
      'stage' : 'Этап',
      'author' : 'Автор',
      'dif' : 'Сложность',
    }

sigmageo_root/editing/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.core.mail import send_mail, get_connection
from .forms import TaskEditor
from collection.database_connection import task
from collection.models import Problem

def add_task(request):
  
  if request.method == 'POST':
    new_task = Problem(num = request.POST['num'],
                       grade = request.POST['grade'],
                       text = request.POST['text'],
                       solution = request.POST['solution'],
                       themes = request.POST['themes'],
                       source = request.POST['source'],
                       year = request.POST['year'],
                       stage = request.POST['stage'],
                       author = request.POST['author'],
                       dif = int(request.POST['dif']))
    new_task.save()

  context = {
    'title': 'Новая задача',
    'is_admin': request.user.groups.filter(name='admin').exists(),
  }

  return render(request, 'pages/add_task.html', context)

def redact_task(request):

  id = request.GET['id']

  if request.method == 'POST':
    problem = Problem.objects.get(id = id)
    problem.num = request.POST['num']
    problem.grade = request.POST['grade']
    problem.text = request.POST['text']
    problem.solution = request.POST['solution']
    problem.themes = request.POST['themes']
    problem.source = request.POST['source']
    problem.year = request.POST['year']
    problem.stage = request.POST['stage']
    problem.author = request.POST['author']
    problem.dif = int(request.POST['dif'])
    problem.save(update_fields=['num', 'grade', 'text', 'solution', 'themes', 'source', 'year', 'stage', 'author', 'dif'])
    
    return HttpResponseRedirect(f'/sigma_geo/problem?id={id}')

  context = {
    'title': 'Редактирование',
    'is_admin': request.user.groups.filter(name='admin').exists(),
    'task': task(id),
  }

  return render(request, 'pages/redact_task.html', context)

def add_section(request):

  context = {
    'title': 'Новый раздел',
    'is_admin': request.user.groups.filter(name='admin').exists()
  }

  return render(request, 'pages/add_section.html', context)

def redact_section(request):

  context = {
    'title': 'Редактирование',
    'is_admin': request.user.groups.filter(name='admin').exists()
  }

  return render(request, 'pages/redact_section.html', context)

def p404(request, *args, **kwargs):
  return render(request, 'pages/404.html', {'title': 'Ошибка'})

sigmageo_root/editing/templates/pages/add_task.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{ title }}{% endblock title %}

{% block content %}

<div class="crutch_section"></div>

<form action="" method="POST">
  {% csrf_token %}

  <table>

  <tr>
    <th><label for="id_num">Номер:</label></th>
    <td>
      <input type="text" name="num" maxlength="5" required id="id_num" null="True">
    </td>
  </tr>

  <tr>
    <th><label for="id_grade">Класс:</label></th>
    <td>
      <input type="text" name="grade" maxlength="5" required id="id_grade" null="True">
    </td>
  </tr>

  <tr>
    <th><label for="id_text">Условие:</label></th>
    <td>
      <textarea name="text" cols="40" rows="10" required id="id_text"></textarea>
    </td>
  </tr>

  <tr>
    <th><label for="id_solution">Решение:</label></th>
    <td>
      <textarea name="solution" cols="40" rows="10" required id="id_solution" null="True"></textarea>
    </td>
  </tr>

  <tr>
    <th><label for="id_themes">Темы:</label></th>
    <td>
      <textarea name="themes" cols="40" rows="10" required id="id_themes">[]</textarea>
    </td>
  </tr>

  <tr>
    <th><label for="id_source">Источник:</label></th>
    <td>
      <input type="text" name="source" maxlength="250" required id="id_source" null="True">
    </td>
  </tr>

  <tr>
    <th><label for="id_year">Год:</label></th>
    <td>
      <input type="text" name="year" maxlength="20" required id="id_year" null="True">
    </td>
  </tr>

  <tr>
    <th><label for="id_stage">Этап:</label></th>
    <td>
      <input type="text" name="stage" maxlength="150" required id="id_stage" null="True">
    </td>
  </tr>

  <tr>
    <th><label for="id_author">Автор:</label></th>
    <td>
      <input type="text" name="author" maxlength="150" required id="id_author" null="True">
    </td>
  </tr>

  <tr>
    <th><label for="id_dif">Сложность:</label></th>
    <td>
      <select name="dif" required id="id_dif">
        <option value="0" selected>0</option>
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
        <option value="6">6</option>
        <option value="7">7</option>
        <option value="8">8</option>
        <option value="9">9</option>
        <option value="10">10</option>

      </select>
    </td>
  </tr>

  </table>
  <input type="submit" value="Сохранить">
</form>



{% endblock content %}

sigmageo_root/editing/templates/pages/redact_task.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{ title }}{% endblock title %}

{% block content %}

<div class="crutch_section"></div>

<form action="" method="POST" novalidate>
  {% csrf_token %}

  <table>
    <tr>
    <th><label for="id_id">Id:</label></th>
    <td>
      {{task.id}}
    </td>
  </tr>

  <tr>
    <th><label for="id_num">Номер:</label></th>
    <td>
      <input type="text" name="num" maxlength="5" required id="id_num" value="{{task.num}}">
    </td>
  </tr>

  <tr>
    <th><label for="id_grade">Класс:</label></th>
    <td>
      <input type="text" name="grade" maxlength="5" required id="id_grade" value="{{task.grade}}">
    </td>
  </tr>

  <tr>
    <th><label for="id_text">Условие:</label></th>
    <td>
      <textarea name="text" cols="40" rows="10" required id="id_text">{{task.text}}</textarea>
    </td>
  </tr>

  <tr>
    <th><label for="id_solution">Решение:</label></th>
    <td>
      <textarea name="solution" cols="40" rows="10" required id="id_solution">{{task.solution}}</textarea>
    </td>
  </tr>

  <tr>
    <th><label for="id_themes">Темы:</label></th>
    <td>
      <textarea name="themes" cols="40" rows="10" required id="id_themes">{{task.themes}}</textarea>
    </td>
  </tr>

  <tr>
    <th><label for="id_source">Источник:</label></th>
    <td>
      <input type="text" name="source" maxlength="250" required id="id_source" value="{{task.source}}">
    </td>
  </tr>

  <tr>
    <th><label for="id_year">Год:</label></th>
    <td>
      <input type="text" name="year" maxlength="20" required id="id_year" value="{{task.year}}">
    </td>
  </tr>

  <tr>
    <th><label for="id_stage">Этап:</label></th>
    <td>
      <input type="text" name="stage" maxlength="150" required id="id_stage" value="{{task.stage}}">
    </td>
  </tr>

  <tr>
    <th><label for="id_author">Автор:</label></th>
    <td>
      <input type="text" name="author" maxlength="150" required id="id_author" value="{{task.author}}">
    </td>
  </tr>

  <tr>
    <th><label for="id_dif">Сложность:</label></th>
    <td>
      <select name="dif" required id="id_dif">
        <option value="0" selected>0</option>
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
        <option value="6">6</option>
        <option value="7">7</option>
        <option value="8">8</option>
        <option value="9">9</option>
        <option value="10">10</option>
      </select>
    </td>
  </tr>

  </table>
  <input type="submit" value="Сохранить">
  
</form>



{% endblock content %}